services:
  postgresdb:
    image: postgres:17.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: naratta_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d naratta_db" ]
      interval: 10s
      retries: 2
      start_period: 30s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: naratta-server
    depends_on:
      postgresdb:
        condition: service_healthy
    ports:
      - "8000:8000"
  
volumes:
  postgres_data:
    driver: local